=== DmytroPavlyshyn/task13_XML/src/main/resources/xml/banksXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="banks"
           xmlns="banks"
           elementFormDefault="qualified">


    <xs:simpleType name="deposit_type" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="question"/>
            <xs:enumeration value="express"/>
            <xs:enumeration value="calculated"/>
            <xs:enumeration value="accumulative"/>
            <xs:enumeration value="saving"/>
            <xs:enumeration value="metallic"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="percent">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="banks">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="bank" type='bankType' minOccurs='0'
                            maxOccurs='unbounded'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="bankType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="country" type="xs:string"/>

            <xs:element name="deposit_types">

                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="deposit_type" type="deposit_type"/>
                    </xs:sequence>
                </xs:complexType>

            </xs:element>
            <xs:element name="depositor" type="xs:string"/>
            <xs:element name="account_id" type="xs:integer"/>
            <xs:element name="amount_on_deposit" type="xs:integer"/>
            <xs:element name="profitability" type="percent"/>
            <xs:element name="time_constraints" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="bank_id" type='xs:integer'/>
    </xs:complexType>
</xs:schema>

=== DmytroPavlyshyn/task13_XML/src/main/resources/xml/banksXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<?xml-stylesheet type="text/xsl" href="beerXSLT.xsl"?>-->

<banks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:schemaLocation = "banksXSD.xsd"
       xmlns="banks">
    <bank bank_id="0">
        <name>golden ale</name>
        <country>golden ale</country>

        <deposit_types>
            <deposit_type>calculated</deposit_type>
            <deposit_type>express</deposit_type>
        </deposit_types>

        <depositor>Jone Dove</depositor>
        <account_id>45</account_id>
        <amount_on_deposit>156</amount_on_deposit>
        <profitability>100</profitability>
        <time_constraints>2020-04-24</time_constraints>
    </bank>
</banks>
